### ISSUE TITLE
Adapter Error

### ISSUE THREAD

**Issue by Starter4711** [fungus75/ioBroker.zoe#5]
Hello, adapter terminates without reason?
<img width="871" alt="Bildschirmfoto 2021-02-18 um 15 05 37" src="https://user-images.githubusercontent.com/15359915/108368565-e6085300-71fa-11eb-87d3-5c1b2958603c.png">

**Comment by marv2622** [comment]
Having the same problem like you.
Log:
zoe2.0	2021-02-23 09:45:08.784	error	(26128) Cannot read property 'personId' of undefined
zoe2.0	2021-02-23 09:45:08.783	error	at processTicksAndRejections (internal/process/task_queues.js:84:21)
zoe2.0	2021-02-23 09:45:08.783	error	at endReadableNT (_stream_readable.js:1241:12)
zoe2.0	2021-02-23 09:45:08.783	error	at IncomingMessage.emit (events.js:326:22)
zoe2.0	2021-02-23 09:45:08.783	error	at Object.onceWrapper (events.js:420:28)
zoe2.0	2021-02-23 09:45:08.783	error	at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/iobroker.zoe2/node_modules/request/request.js:1076:12)
zoe2.0	2021-02-23 09:45:08.783	error	at Request.emit (events.js:314:20)
zoe2.0	2021-02-23 09:45:08.783	error	at Request.<anonymous> (/opt/iobroker/node_modules/iobroker.zoe2/node_modules/request/request.js:1154:10)
zoe2.0	2021-02-23 09:45:08.783	error	at Request.emit (events.js:314:20)
zoe2.0	2021-02-23 09:45:08.783	error	at Request.self.callback (/opt/iobroker/node_modules/iobroker.zoe2/node_modules/request/request.js:185:22)
zoe2.0	2021-02-23 09:45:08.783	error	at Request._callback (/opt/iobroker/node_modules/iobroker.zoe2/main.js:250:44)
